import { chromium, expect, request } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

const baseURL = process.env.TEST_BASE_URL;
if (!baseURL?.startsWith('https://')) throw new Error('Set TEST_BASE_URL to the HTTPS preview URL. Production session cookies require HTTPS.');
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const screenshot = async options => {
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.waitForTimeout(450);
  return page.screenshot(options);
};
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const getData = async () => { const res = await context.request.get('/api/driver/dashboard'); assert.equal(res.status(), 200); return res.json(); };
const nav = index => page.locator('.nav-item').nth(index).click();
const waitData = async predicate => expect.poll(async () => predicate(await getData())).toBe(true);
try {
  await page.goto('/', { waitUntil: 'networkidle' });
  await expect(page.locator('.hero-banner')).toBeVisible({ timeout: 30000 });
  await page.evaluate(() => document.fonts.ready);
  const initial = await getData();
  assert.equal(initial.driver.status, 'approved');
  assert.equal(initial.stats.deliveredToday, 24);
  assert.equal(initial.stats.today, 36000);
  assert.ok(initial.available.length > 0);
  for (const order of initial.mine) assert.equal(order.items.reduce((sum, item) => sum + item.quantity * item.price, 0), order.total);
  await screenshot({ path: 'artifacts/dashboard-desktop.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  console.log('PASS: dashboard, correct totals, and desktop layout');

  await page.getByRole('switch').click();
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'false');
  await page.getByRole('button', { name: 'Find available orders', exact: true }).click();
  await page.locator('.order-detail-button').first().click();
  await expect(page.getByRole('button', { name: 'Go online to accept orders', exact: true })).toBeDisabled();
  await page.keyboard.press('Escape');
  await page.getByRole('switch').click();
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'true');
  const available = (await getData()).available[0];
  await page.locator('.order-card').filter({ hasText: available.code }).getByRole('button', { name: 'View details', exact: true }).click();
  await page.getByRole('button', { name: 'Accept this delivery', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirm pickup', exact: true })).toBeVisible();
  await waitData(d => d.mine.some(o => o.id === available.id && o.status === 'accepted'));
  await page.getByRole('button', { name: 'Confirm pickup', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Start delivery', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Start delivery', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mark as delivered', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Customer chat', exact: true }).click();
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('I’m on my way. Browser integration check.');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.locator('.chat-message.mine')).toContainText('Browser integration check.');
  const savedChat = await (await context.request.get(`/api/driver/orders/${available.id}/chat`)).json();
  assert.ok(savedChat.messages.some(m => m.text.includes('Browser integration check.')));
  await page.getByRole('button', { name: 'Order details', exact: true }).click();
  await page.getByRole('button', { name: 'Mark as delivered', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Back to deliveries', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back to deliveries', exact: true }).click();
  const delivered = await getData();
  assert.equal(delivered.driver.walletBalance, initial.driver.walletBalance - available.commission);
  assert.equal(delivered.stats.today, initial.stats.today + available.deliveryFee);
  const duplicate = await context.request.patch(`/api/driver/orders/${available.id}`, { data: { status: 'delivered' } });
  assert.equal(duplicate.status(), 409);
  assert.equal((await getData()).driver.walletBalance, delivered.driver.walletBalance);
  console.log('PASS: availability, acceptance, status transitions, saved chat, and idempotent wallet charge');

  await nav(3);
  await page.getByRole('button', { name: 'Top up wallet', exact: true }).click();
  await page.getByRole('button', { name: '250 MAD', exact: true }).click();
  await page.locator('.receipt-upload input').setInputFiles('public/icons/icon-192.png');
  await expect(page.getByRole('button', { name: 'Submit top-up request', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Submit top-up request', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await waitData(d => d.topups.some(t => t.amount === 25000 && t.status === 'pending' && t.hasReceipt));
  const walletData = await getData();
  assert.equal(walletData.driver.walletBalance, delivered.driver.walletBalance);
  const topup = walletData.topups.find(t => t.amount === 25000 && t.status === 'pending');
  const receipt = await context.request.get(`/api/driver/topups/${topup.id}/receipt`);
  assert.equal(receipt.status(), 200);
  assert.match(receipt.headers()['content-type'], /image\/jpeg/);
  await screenshot({ path: 'artifacts/wallet-desktop.png', fullPage: true });
  console.log('PASS: image receipt, pending top-up persistence, and protected receipt viewing');

  await nav(4);
  await page.getByLabel('Full name', { exact: true }).fill('Yassine Benali Test');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.locator('.profile-overview h2')).toHaveText('Yassine Benali Test');
  await page.reload({ waitUntil: 'networkidle' });
  await expect(page.locator('.profile-overview h2')).toHaveText('Yassine Benali Test');
  await page.locator('.help-card button').click();
  await page.getByLabel('How can we help?', { exact: true }).selectOption('Wallet and payments');
  await page.getByLabel('Your message', { exact: true }).fill('Please help me verify the bank account for my next wallet transfer.');
  await page.getByRole('button', { name: 'Send support request', exact: true }).click();
  await expect(page.locator('.ticket-reference')).toBeVisible();
  await page.keyboard.press('Escape');
  console.log('PASS: saved profile and persisted support ticket');

  await page.locator('.language-button').click();
  await page.locator('.language-popover').getByRole('button', { name: /Français/ }).click();
  await expect(page.locator('html')).toHaveAttribute('lang', 'fr');
  await page.locator('.language-button').click();
  await page.locator('.language-popover').getByRole('button', { name: /العربية/ }).click();
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl');
  await nav(0);
  await screenshot({ path: 'artifacts/dashboard-arabic.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.setViewportSize({ width: 390, height: 844 });
  await screenshot({ path: 'artifacts/dashboard-mobile-arabic.png', fullPage: false });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('.mobile-menu-button').click();
  await expect(page.locator('.sidebar')).toHaveClass(/sidebar-open/);
  await nav(2);
  await expect(page.locator('.sidebar')).not.toHaveClass(/sidebar-open/);
  await page.locator('.language-button').click();
  await page.locator('.language-popover').getByRole('button', { name: /English/ }).click();
  await page.locator('.mobile-menu-button').click();
  await nav(0);
  await screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: false });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  console.log('PASS: French, Arabic RTL, mobile navigation, and responsive layout');

  const anonymous = await request.newContext({ baseURL });
  assert.equal((await anonymous.get('/api/driver/me')).status(), 401);
  assert.equal((await anonymous.get(`/api/driver/topups/${topup.id}/receipt`)).status(), 401);
  await anonymous.dispose();
  const blockedDelete = await context.request.delete('/api/driver/me', { data: { confirmation: 'DELETE' } });
  assert.equal(blockedDelete.status(), 409);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await nav(4);
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await expect(page.locator('.auth-page')).toBeVisible();
  await page.getByRole('button', { name: 'Sign up', exact: true }).click();
  const email = `browser-${Date.now()}@example.test`;
  await page.getByLabel('Full name', { exact: true }).fill('Browser Test Driver');
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('SafeTestPassword2026!');
  await page.getByLabel('Confirm password', { exact: true }).fill('NotTheSamePassword!');
  await page.getByRole('button', { name: 'Create driver account', exact: true }).click();
  await expect(page.locator('.auth-form [role="alert"]')).toContainText('Passwords do not match');
  await page.getByLabel('Confirm password', { exact: true }).fill('SafeTestPassword2026!');
  await page.getByRole('button', { name: 'Create driver account', exact: true }).click();
  await expect(page.locator('.pending-banner')).toBeVisible();
  const newDriver = await getData();
  assert.equal(newDriver.driver.status, 'pending');
  assert.equal(newDriver.mine.length, 0);
  assert.equal((await context.request.post(`/api/driver/orders/${available.id}/accept`, { data: {} })).status(), 403);
  await nav(4);
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('SafeTestPassword2026!');
  await page.getByRole('button', { name: 'Let’s get moving', exact: true }).click();
  await expect(page.locator('.pending-banner')).toBeVisible();
  await nav(4);
  await page.getByRole('button', { name: 'Delete account', exact: true }).click();
  await page.getByLabel('Type DELETE to confirm', { exact: true }).fill('DELETE');
  await page.getByRole('button', { name: 'Permanently delete account', exact: true }).click();
  await expect(page.locator('.auth-page')).toBeVisible();
  await screenshot({ path: 'artifacts/login-desktop.png', fullPage: true });
  assert.equal((await context.request.get('/api/driver/me')).status(), 401);
  assert.deepEqual(errors, []);
  console.log('PASS: access control, password validation, signup, pending approval, login, logout, and account deletion');
  console.log('All browser workflow checks passed. No browser runtime errors.');
} catch (error) {
  await screenshot({ path: 'artifacts/test-failure.png', fullPage: true }).catch(() => {});
  console.error(error);
  process.exitCode = 1;
} finally {
  await context.close();
  await browser.close();
}
